// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chainpulse.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	UserAddr      string                 `protobuf:"bytes,4,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	TokenA        string                 `protobuf:"bytes,5,opt,name=token_a,json=tokenA,proto3" json:"token_a,omitempty"`
	AmountA       string                 `protobuf:"bytes,6,opt,name=amount_a,json=amountA,proto3" json:"amount_a,omitempty"`
	Params        string                 `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionRow) Reset() {
	*x = PositionRow{}
	mi := &file_chainpulse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionRow) ProtoMessage() {}

func (x *PositionRow) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionRow.ProtoReflect.Descriptor instead.
func (*PositionRow) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{0}
}

func (x *PositionRow) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *PositionRow) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PositionRow) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PositionRow) GetUserAddr() string {
	if x != nil {
		return x.UserAddr
	}
	return ""
}

func (x *PositionRow) GetTokenA() string {
	if x != nil {
		return x.TokenA
	}
	return ""
}

func (x *PositionRow) GetAmountA() string {
	if x != nil {
		return x.AmountA
	}
	return ""
}

func (x *PositionRow) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *PositionRow) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HistoryRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	LogIndex      uint32                 `protobuf:"varint,4,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	UserAddr      string                 `protobuf:"bytes,7,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	TokenA        string                 `protobuf:"bytes,8,opt,name=token_a,json=tokenA,proto3" json:"token_a,omitempty"`
	AmountA       string                 `protobuf:"bytes,9,opt,name=amount_a,json=amountA,proto3" json:"amount_a,omitempty"`
	Params        string                 `protobuf:"bytes,10,opt,name=params,proto3" json:"params,omitempty"`
	Timestamp     int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRow) Reset() {
	*x = HistoryRow{}
	mi := &file_chainpulse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRow) ProtoMessage() {}

func (x *HistoryRow) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRow.ProtoReflect.Descriptor instead.
func (*HistoryRow) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryRow) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *HistoryRow) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *HistoryRow) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *HistoryRow) GetLogIndex() uint32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *HistoryRow) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HistoryRow) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HistoryRow) GetUserAddr() string {
	if x != nil {
		return x.UserAddr
	}
	return ""
}

func (x *HistoryRow) GetTokenA() string {
	if x != nil {
		return x.TokenA
	}
	return ""
}

func (x *HistoryRow) GetAmountA() string {
	if x != nil {
		return x.AmountA
	}
	return ""
}

func (x *HistoryRow) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *HistoryRow) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TransferRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	LogIndex      uint32                 `protobuf:"varint,4,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	FromAddr      string                 `protobuf:"bytes,6,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	ToAddr        string                 `protobuf:"bytes,7,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	Amount        string                 `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRow) Reset() {
	*x = TransferRow{}
	mi := &file_chainpulse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRow) ProtoMessage() {}

func (x *TransferRow) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRow.ProtoReflect.Descriptor instead.
func (*TransferRow) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{2}
}

func (x *TransferRow) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *TransferRow) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TransferRow) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransferRow) GetLogIndex() uint32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *TransferRow) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TransferRow) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *TransferRow) GetToAddr() string {
	if x != nil {
		return x.ToAddr
	}
	return ""
}

func (x *TransferRow) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferRow) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ProtocolStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	EventCount    uint64                 `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	UniqueUsers   uint64                 `protobuf:"varint,4,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	LastSeen      int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolStat) Reset() {
	*x = ProtocolStat{}
	mi := &file_chainpulse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolStat) ProtoMessage() {}

func (x *ProtocolStat) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolStat.ProtoReflect.Descriptor instead.
func (*ProtocolStat) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolStat) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ProtocolStat) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolStat) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *ProtocolStat) GetUniqueUsers() uint64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

func (x *ProtocolStat) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type BlockSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	EventCount    uint64                 `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	LatestTs      int64                  `protobuf:"varint,4,opt,name=latest_ts,json=latestTs,proto3" json:"latest_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSummary) Reset() {
	*x = BlockSummary{}
	mi := &file_chainpulse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSummary) ProtoMessage() {}

func (x *BlockSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSummary.ProtoReflect.Descriptor instead.
func (*BlockSummary) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{4}
}

func (x *BlockSummary) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *BlockSummary) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockSummary) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *BlockSummary) GetLatestTs() int64 {
	if x != nil {
		return x.LatestTs
	}
	return 0
}

type GetWalletPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        string                 `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletPositionsRequest) Reset() {
	*x = GetWalletPositionsRequest{}
	mi := &file_chainpulse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletPositionsRequest) ProtoMessage() {}

func (x *GetWalletPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetWalletPositionsRequest) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{5}
}

func (x *GetWalletPositionsRequest) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *GetWalletPositionsRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetWalletPositionsRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type GetWalletPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*PositionRow         `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletPositionsResponse) Reset() {
	*x = GetWalletPositionsResponse{}
	mi := &file_chainpulse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletPositionsResponse) ProtoMessage() {}

func (x *GetWalletPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetWalletPositionsResponse) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{6}
}

func (x *GetWalletPositionsResponse) GetPositions() []*PositionRow {
	if x != nil {
		return x.Positions
	}
	return nil
}

type GetWalletBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        string                 `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalancesRequest) Reset() {
	*x = GetWalletBalancesRequest{}
	mi := &file_chainpulse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalancesRequest) ProtoMessage() {}

func (x *GetWalletBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetWalletBalancesRequest) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{7}
}

func (x *GetWalletBalancesRequest) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *GetWalletBalancesRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type GetWalletBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Balances      map[string]string      `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // token -> amount (uint256 as decimal string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalancesResponse) Reset() {
	*x = GetWalletBalancesResponse{}
	mi := &file_chainpulse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalancesResponse) ProtoMessage() {}

func (x *GetWalletBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetWalletBalancesResponse) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{8}
}

func (x *GetWalletBalancesResponse) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetWalletBalancesResponse) GetBalances() map[string]string {
	if x != nil {
		return x.Balances
	}
	return nil
}

type GetWalletHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        string                 `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletHistoryRequest) Reset() {
	*x = GetWalletHistoryRequest{}
	mi := &file_chainpulse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletHistoryRequest) ProtoMessage() {}

func (x *GetWalletHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWalletHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{9}
}

func (x *GetWalletHistoryRequest) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *GetWalletHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetWalletHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*HistoryRow          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletHistoryResponse) Reset() {
	*x = GetWalletHistoryResponse{}
	mi := &file_chainpulse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletHistoryResponse) ProtoMessage() {}

func (x *GetWalletHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetWalletHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{10}
}

func (x *GetWalletHistoryResponse) GetEvents() []*HistoryRow {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetTokenTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenTransfersRequest) Reset() {
	*x = GetTokenTransfersRequest{}
	mi := &file_chainpulse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenTransfersRequest) ProtoMessage() {}

func (x *GetTokenTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenTransfersRequest.ProtoReflect.Descriptor instead.
func (*GetTokenTransfersRequest) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{11}
}

func (x *GetTokenTransfersRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTokenTransfersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTokenTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*TransferRow         `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenTransfersResponse) Reset() {
	*x = GetTokenTransfersResponse{}
	mi := &file_chainpulse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenTransfersResponse) ProtoMessage() {}

func (x *GetTokenTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenTransfersResponse.ProtoReflect.Descriptor instead.
func (*GetTokenTransfersResponse) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{12}
}

func (x *GetTokenTransfersResponse) GetTransfers() []*TransferRow {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type GetProtocolStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolStatsRequest) Reset() {
	*x = GetProtocolStatsRequest{}
	mi := &file_chainpulse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolStatsRequest) ProtoMessage() {}

func (x *GetProtocolStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolStatsRequest.ProtoReflect.Descriptor instead.
func (*GetProtocolStatsRequest) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{13}
}

func (x *GetProtocolStatsRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *GetProtocolStatsRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type GetProtocolStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*ProtocolStat        `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolStatsResponse) Reset() {
	*x = GetProtocolStatsResponse{}
	mi := &file_chainpulse_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolStatsResponse) ProtoMessage() {}

func (x *GetProtocolStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolStatsResponse.ProtoReflect.Descriptor instead.
func (*GetProtocolStatsResponse) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{14}
}

func (x *GetProtocolStatsResponse) GetStats() []*ProtocolStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetChainBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainBlocksRequest) Reset() {
	*x = GetChainBlocksRequest{}
	mi := &file_chainpulse_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainBlocksRequest) ProtoMessage() {}

func (x *GetChainBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetChainBlocksRequest) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{15}
}

func (x *GetChainBlocksRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetChainBlocksRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetChainBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockSummary        `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainBlocksResponse) Reset() {
	*x = GetChainBlocksResponse{}
	mi := &file_chainpulse_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainBlocksResponse) ProtoMessage() {}

func (x *GetChainBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainpulse_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetChainBlocksResponse) Descriptor() ([]byte, []int) {
	return file_chainpulse_proto_rawDescGZIP(), []int{16}
}

func (x *GetChainBlocksResponse) GetBlocks() []*BlockSummary {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_chainpulse_proto protoreflect.FileDescriptor

const file_chainpulse_proto_rawDesc = "" +
	"\n" +
	"\x10chainpulse.proto\x12\rchainpulse.v1\"\xea\x01\n" +
	"\vPositionRow\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1b\n" +
	"\tuser_addr\x18\x04 \x01(\tR\buserAddr\x12\x17\n" +
	"\atoken_a\x18\x05 \x01(\tR\x06tokenA\x12\x19\n" +
	"\bamount_a\x18\x06 \x01(\tR\aamountA\x12\x16\n" +
	"\x06params\x18\a \x01(\tR\x06params\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\xc2\x02\n" +
	"\n" +
	"HistoryRow\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x1b\n" +
	"\tlog_index\x18\x04 \x01(\rR\blogIndex\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12\x1b\n" +
	"\tuser_addr\x18\a \x01(\tR\buserAddr\x12\x17\n" +
	"\atoken_a\x18\b \x01(\tR\x06tokenA\x12\x19\n" +
	"\bamount_a\x18\t \x01(\tR\aamountA\x12\x16\n" +
	"\x06params\x18\n" +
	" \x01(\tR\x06params\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\"\x83\x02\n" +
	"\vTransferRow\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x1b\n" +
	"\tlog_index\x18\x04 \x01(\rR\blogIndex\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x1b\n" +
	"\tfrom_addr\x18\x06 \x01(\tR\bfromAddr\x12\x17\n" +
	"\ato_addr\x18\a \x01(\tR\x06toAddr\x12\x16\n" +
	"\x06amount\x18\b \x01(\tR\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\xa6\x01\n" +
	"\fProtocolStat\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\x04R\n" +
	"eventCount\x12!\n" +
	"\funique_users\x18\x04 \x01(\x04R\vuniqueUsers\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen\"\x8a\x01\n" +
	"\fBlockSummary\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\x04R\n" +
	"eventCount\x12\x1b\n" +
	"\tlatest_ts\x18\x04 \x01(\x03R\blatestTs\"j\n" +
	"\x19GetWalletPositionsRequest\x12\x16\n" +
	"\x06wallet\x18\x01 \x01(\tR\x06wallet\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"V\n" +
	"\x1aGetWalletPositionsResponse\x128\n" +
	"\tpositions\x18\x01 \x03(\v2\x1a.chainpulse.v1.PositionRowR\tpositions\"M\n" +
	"\x18GetWalletBalancesRequest\x12\x16\n" +
	"\x06wallet\x18\x01 \x01(\tR\x06wallet\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\"\xc7\x01\n" +
	"\x19GetWalletBalancesResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12R\n" +
	"\bbalances\x18\x02 \x03(\v26.chainpulse.v1.GetWalletBalancesResponse.BalancesEntryR\bbalances\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x17GetWalletHistoryRequest\x12\x16\n" +
	"\x06wallet\x18\x01 \x01(\tR\x06wallet\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"M\n" +
	"\x18GetWalletHistoryResponse\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.chainpulse.v1.HistoryRowR\x06events\"F\n" +
	"\x18GetTokenTransfersRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"U\n" +
	"\x19GetTokenTransfersResponse\x128\n" +
	"\ttransfers\x18\x01 \x03(\v2\x1a.chainpulse.v1.TransferRowR\ttransfers\"P\n" +
	"\x17GetProtocolStatsRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\"M\n" +
	"\x18GetProtocolStatsResponse\x121\n" +
	"\x05stats\x18\x01 \x03(\v2\x1b.chainpulse.v1.ProtocolStatR\x05stats\"H\n" +
	"\x15GetChainBlocksRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"M\n" +
	"\x16GetChainBlocksResponse\x123\n" +
	"\x06blocks\x18\x01 \x03(\v2\x1b.chainpulse.v1.BlockSummaryR\x06blocks2\xc0\x02\n" +
	"\x06Wallet\x12i\n" +
	"\x12GetWalletPositions\x12(.chainpulse.v1.GetWalletPositionsRequest\x1a).chainpulse.v1.GetWalletPositionsResponse\x12f\n" +
	"\x11GetWalletBalances\x12'.chainpulse.v1.GetWalletBalancesRequest\x1a(.chainpulse.v1.GetWalletBalancesResponse\x12c\n" +
	"\x10GetWalletHistory\x12&.chainpulse.v1.GetWalletHistoryRequest\x1a'.chainpulse.v1.GetWalletHistoryResponse2o\n" +
	"\x05Token\x12f\n" +
	"\x11GetTokenTransfers\x12'.chainpulse.v1.GetTokenTransfersRequest\x1a(.chainpulse.v1.GetTokenTransfersResponse2o\n" +
	"\bProtocol\x12c\n" +
	"\x10GetProtocolStats\x12&.chainpulse.v1.GetProtocolStatsRequest\x1a'.chainpulse.v1.GetProtocolStatsResponse2f\n" +
	"\x05Chain\x12]\n" +
	"\x0eGetChainBlocks\x12$.chainpulse.v1.GetChainBlocksRequest\x1a%.chainpulse.v1.GetChainBlocksResponseB8Z6github.com/0xfandom/chainpulse/internal/api/grpc/pb;pbb\x06proto3"

var (
	file_chainpulse_proto_rawDescOnce sync.Once
	file_chainpulse_proto_rawDescData []byte
)

func file_chainpulse_proto_rawDescGZIP() []byte {
	file_chainpulse_proto_rawDescOnce.Do(func() {
		file_chainpulse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chainpulse_proto_rawDesc), len(file_chainpulse_proto_rawDesc)))
	})
	return file_chainpulse_proto_rawDescData
}

var file_chainpulse_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_chainpulse_proto_goTypes = []any{
	(*PositionRow)(nil),                // 0: chainpulse.v1.PositionRow
	(*HistoryRow)(nil),                 // 1: chainpulse.v1.HistoryRow
	(*TransferRow)(nil),                // 2: chainpulse.v1.TransferRow
	(*ProtocolStat)(nil),               // 3: chainpulse.v1.ProtocolStat
	(*BlockSummary)(nil),               // 4: chainpulse.v1.BlockSummary
	(*GetWalletPositionsRequest)(nil),  // 5: chainpulse.v1.GetWalletPositionsRequest
	(*GetWalletPositionsResponse)(nil), // 6: chainpulse.v1.GetWalletPositionsResponse
	(*GetWalletBalancesRequest)(nil),   // 7: chainpulse.v1.GetWalletBalancesRequest
	(*GetWalletBalancesResponse)(nil),  // 8: chainpulse.v1.GetWalletBalancesResponse
	(*GetWalletHistoryRequest)(nil),    // 9: chainpulse.v1.GetWalletHistoryRequest
	(*GetWalletHistoryResponse)(nil),   // 10: chainpulse.v1.GetWalletHistoryResponse
	(*GetTokenTransfersRequest)(nil),   // 11: chainpulse.v1.GetTokenTransfersRequest
	(*GetTokenTransfersResponse)(nil),  // 12: chainpulse.v1.GetTokenTransfersResponse
	(*GetProtocolStatsRequest)(nil),    // 13: chainpulse.v1.GetProtocolStatsRequest
	(*GetProtocolStatsResponse)(nil),   // 14: chainpulse.v1.GetProtocolStatsResponse
	(*GetChainBlocksRequest)(nil),      // 15: chainpulse.v1.GetChainBlocksRequest
	(*GetChainBlocksResponse)(nil),     // 16: chainpulse.v1.GetChainBlocksResponse
	nil,                                // 17: chainpulse.v1.GetWalletBalancesResponse.BalancesEntry
}
var file_chainpulse_proto_depIdxs = []int32{
	0,  // 0: chainpulse.v1.GetWalletPositionsResponse.positions:type_name -> chainpulse.v1.PositionRow
	17, // 1: chainpulse.v1.GetWalletBalancesResponse.balances:type_name -> chainpulse.v1.GetWalletBalancesResponse.BalancesEntry
	1,  // 2: chainpulse.v1.GetWalletHistoryResponse.events:type_name -> chainpulse.v1.HistoryRow
	2,  // 3: chainpulse.v1.GetTokenTransfersResponse.transfers:type_name -> chainpulse.v1.TransferRow
	3,  // 4: chainpulse.v1.GetProtocolStatsResponse.stats:type_name -> chainpulse.v1.ProtocolStat
	4,  // 5: chainpulse.v1.GetChainBlocksResponse.blocks:type_name -> chainpulse.v1.BlockSummary
	5,  // 6: chainpulse.v1.Wallet.GetWalletPositions:input_type -> chainpulse.v1.GetWalletPositionsRequest
	7,  // 7: chainpulse.v1.Wallet.GetWalletBalances:input_type -> chainpulse.v1.GetWalletBalancesRequest
	9,  // 8: chainpulse.v1.Wallet.GetWalletHistory:input_type -> chainpulse.v1.GetWalletHistoryRequest
	11, // 9: chainpulse.v1.Token.GetTokenTransfers:input_type -> chainpulse.v1.GetTokenTransfersRequest
	13, // 10: chainpulse.v1.Protocol.GetProtocolStats:input_type -> chainpulse.v1.GetProtocolStatsRequest
	15, // 11: chainpulse.v1.Chain.GetChainBlocks:input_type -> chainpulse.v1.GetChainBlocksRequest
	6,  // 12: chainpulse.v1.Wallet.GetWalletPositions:output_type -> chainpulse.v1.GetWalletPositionsResponse
	8,  // 13: chainpulse.v1.Wallet.GetWalletBalances:output_type -> chainpulse.v1.GetWalletBalancesResponse
	10, // 14: chainpulse.v1.Wallet.GetWalletHistory:output_type -> chainpulse.v1.GetWalletHistoryResponse
	12, // 15: chainpulse.v1.Token.GetTokenTransfers:output_type -> chainpulse.v1.GetTokenTransfersResponse
	14, // 16: chainpulse.v1.Protocol.GetProtocolStats:output_type -> chainpulse.v1.GetProtocolStatsResponse
	16, // 17: chainpulse.v1.Chain.GetChainBlocks:output_type -> chainpulse.v1.GetChainBlocksResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_chainpulse_proto_init() }
func file_chainpulse_proto_init() {
	if File_chainpulse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chainpulse_proto_rawDesc), len(file_chainpulse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_chainpulse_proto_goTypes,
		DependencyIndexes: file_chainpulse_proto_depIdxs,
		MessageInfos:      file_chainpulse_proto_msgTypes,
	}.Build()
	File_chainpulse_proto = out.File
	file_chainpulse_proto_goTypes = nil
	file_chainpulse_proto_depIdxs = nil
}
