// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: chainpulse.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Wallet_GetWalletPositions_FullMethodName = "/chainpulse.v1.Wallet/GetWalletPositions"
	Wallet_GetWalletBalances_FullMethodName  = "/chainpulse.v1.Wallet/GetWalletBalances"
	Wallet_GetWalletHistory_FullMethodName   = "/chainpulse.v1.Wallet/GetWalletHistory"
)

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletClient interface {
	GetWalletPositions(ctx context.Context, in *GetWalletPositionsRequest, opts ...grpc.CallOption) (*GetWalletPositionsResponse, error)
	GetWalletBalances(ctx context.Context, in *GetWalletBalancesRequest, opts ...grpc.CallOption) (*GetWalletBalancesResponse, error)
	GetWalletHistory(ctx context.Context, in *GetWalletHistoryRequest, opts ...grpc.CallOption) (*GetWalletHistoryResponse, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) GetWalletPositions(ctx context.Context, in *GetWalletPositionsRequest, opts ...grpc.CallOption) (*GetWalletPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletPositionsResponse)
	err := c.cc.Invoke(ctx, Wallet_GetWalletPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetWalletBalances(ctx context.Context, in *GetWalletBalancesRequest, opts ...grpc.CallOption) (*GetWalletBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletBalancesResponse)
	err := c.cc.Invoke(ctx, Wallet_GetWalletBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetWalletHistory(ctx context.Context, in *GetWalletHistoryRequest, opts ...grpc.CallOption) (*GetWalletHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletHistoryResponse)
	err := c.cc.Invoke(ctx, Wallet_GetWalletHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
// All implementations must embed UnimplementedWalletServer
// for forward compatibility.
type WalletServer interface {
	GetWalletPositions(context.Context, *GetWalletPositionsRequest) (*GetWalletPositionsResponse, error)
	GetWalletBalances(context.Context, *GetWalletBalancesRequest) (*GetWalletBalancesResponse, error)
	GetWalletHistory(context.Context, *GetWalletHistoryRequest) (*GetWalletHistoryResponse, error)
	mustEmbedUnimplementedWalletServer()
}

// UnimplementedWalletServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServer struct{}

func (UnimplementedWalletServer) GetWalletPositions(context.Context, *GetWalletPositionsRequest) (*GetWalletPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletPositions not implemented")
}
func (UnimplementedWalletServer) GetWalletBalances(context.Context, *GetWalletBalancesRequest) (*GetWalletBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletBalances not implemented")
}
func (UnimplementedWalletServer) GetWalletHistory(context.Context, *GetWalletHistoryRequest) (*GetWalletHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletHistory not implemented")
}
func (UnimplementedWalletServer) mustEmbedUnimplementedWalletServer() {}
func (UnimplementedWalletServer) testEmbeddedByValue()                {}

// UnsafeWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServer will
// result in compilation errors.
type UnsafeWalletServer interface {
	mustEmbedUnimplementedWalletServer()
}

func RegisterWalletServer(s grpc.ServiceRegistrar, srv WalletServer) {
	// If the following call panics, it indicates UnimplementedWalletServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Wallet_ServiceDesc, srv)
}

func _Wallet_GetWalletPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetWalletPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_GetWalletPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetWalletPositions(ctx, req.(*GetWalletPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetWalletBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetWalletBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_GetWalletBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetWalletBalances(ctx, req.(*GetWalletBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetWalletHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetWalletHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wallet_GetWalletHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetWalletHistory(ctx, req.(*GetWalletHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wallet_ServiceDesc is the grpc.ServiceDesc for Wallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainpulse.v1.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWalletPositions",
			Handler:    _Wallet_GetWalletPositions_Handler,
		},
		{
			MethodName: "GetWalletBalances",
			Handler:    _Wallet_GetWalletBalances_Handler,
		},
		{
			MethodName: "GetWalletHistory",
			Handler:    _Wallet_GetWalletHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainpulse.proto",
}

const (
	Token_GetTokenTransfers_FullMethodName = "/chainpulse.v1.Token/GetTokenTransfers"
)

// TokenClient is the client API for Token service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenClient interface {
	GetTokenTransfers(ctx context.Context, in *GetTokenTransfersRequest, opts ...grpc.CallOption) (*GetTokenTransfersResponse, error)
}

type tokenClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenClient(cc grpc.ClientConnInterface) TokenClient {
	return &tokenClient{cc}
}

func (c *tokenClient) GetTokenTransfers(ctx context.Context, in *GetTokenTransfersRequest, opts ...grpc.CallOption) (*GetTokenTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenTransfersResponse)
	err := c.cc.Invoke(ctx, Token_GetTokenTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServer is the server API for Token service.
// All implementations must embed UnimplementedTokenServer
// for forward compatibility.
type TokenServer interface {
	GetTokenTransfers(context.Context, *GetTokenTransfersRequest) (*GetTokenTransfersResponse, error)
	mustEmbedUnimplementedTokenServer()
}

// UnimplementedTokenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenServer struct{}

func (UnimplementedTokenServer) GetTokenTransfers(context.Context, *GetTokenTransfersRequest) (*GetTokenTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenTransfers not implemented")
}
func (UnimplementedTokenServer) mustEmbedUnimplementedTokenServer() {}
func (UnimplementedTokenServer) testEmbeddedByValue()               {}

// UnsafeTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServer will
// result in compilation errors.
type UnsafeTokenServer interface {
	mustEmbedUnimplementedTokenServer()
}

func RegisterTokenServer(s grpc.ServiceRegistrar, srv TokenServer) {
	// If the following call panics, it indicates UnimplementedTokenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Token_ServiceDesc, srv)
}

func _Token_GetTokenTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).GetTokenTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Token_GetTokenTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).GetTokenTransfers(ctx, req.(*GetTokenTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Token_ServiceDesc is the grpc.ServiceDesc for Token service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Token_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainpulse.v1.Token",
	HandlerType: (*TokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTokenTransfers",
			Handler:    _Token_GetTokenTransfers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainpulse.proto",
}

const (
	Protocol_GetProtocolStats_FullMethodName = "/chainpulse.v1.Protocol/GetProtocolStats"
)

// ProtocolClient is the client API for Protocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtocolClient interface {
	GetProtocolStats(ctx context.Context, in *GetProtocolStatsRequest, opts ...grpc.CallOption) (*GetProtocolStatsResponse, error)
}

type protocolClient struct {
	cc grpc.ClientConnInterface
}

func NewProtocolClient(cc grpc.ClientConnInterface) ProtocolClient {
	return &protocolClient{cc}
}

func (c *protocolClient) GetProtocolStats(ctx context.Context, in *GetProtocolStatsRequest, opts ...grpc.CallOption) (*GetProtocolStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProtocolStatsResponse)
	err := c.cc.Invoke(ctx, Protocol_GetProtocolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtocolServer is the server API for Protocol service.
// All implementations must embed UnimplementedProtocolServer
// for forward compatibility.
type ProtocolServer interface {
	GetProtocolStats(context.Context, *GetProtocolStatsRequest) (*GetProtocolStatsResponse, error)
	mustEmbedUnimplementedProtocolServer()
}

// UnimplementedProtocolServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtocolServer struct{}

func (UnimplementedProtocolServer) GetProtocolStats(context.Context, *GetProtocolStatsRequest) (*GetProtocolStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProtocolStats not implemented")
}
func (UnimplementedProtocolServer) mustEmbedUnimplementedProtocolServer() {}
func (UnimplementedProtocolServer) testEmbeddedByValue()                  {}

// UnsafeProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtocolServer will
// result in compilation errors.
type UnsafeProtocolServer interface {
	mustEmbedUnimplementedProtocolServer()
}

func RegisterProtocolServer(s grpc.ServiceRegistrar, srv ProtocolServer) {
	// If the following call panics, it indicates UnimplementedProtocolServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Protocol_ServiceDesc, srv)
}

func _Protocol_GetProtocolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProtocolStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtocolServer).GetProtocolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Protocol_GetProtocolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtocolServer).GetProtocolStats(ctx, req.(*GetProtocolStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Protocol_ServiceDesc is the grpc.ServiceDesc for Protocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Protocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainpulse.v1.Protocol",
	HandlerType: (*ProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProtocolStats",
			Handler:    _Protocol_GetProtocolStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainpulse.proto",
}

const (
	Chain_GetChainBlocks_FullMethodName = "/chainpulse.v1.Chain/GetChainBlocks"
)

// ChainClient is the client API for Chain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainClient interface {
	GetChainBlocks(ctx context.Context, in *GetChainBlocksRequest, opts ...grpc.CallOption) (*GetChainBlocksResponse, error)
}

type chainClient struct {
	cc grpc.ClientConnInterface
}

func NewChainClient(cc grpc.ClientConnInterface) ChainClient {
	return &chainClient{cc}
}

func (c *chainClient) GetChainBlocks(ctx context.Context, in *GetChainBlocksRequest, opts ...grpc.CallOption) (*GetChainBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChainBlocksResponse)
	err := c.cc.Invoke(ctx, Chain_GetChainBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainServer is the server API for Chain service.
// All implementations must embed UnimplementedChainServer
// for forward compatibility.
type ChainServer interface {
	GetChainBlocks(context.Context, *GetChainBlocksRequest) (*GetChainBlocksResponse, error)
	mustEmbedUnimplementedChainServer()
}

// UnimplementedChainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainServer struct{}

func (UnimplementedChainServer) GetChainBlocks(context.Context, *GetChainBlocksRequest) (*GetChainBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChainBlocks not implemented")
}
func (UnimplementedChainServer) mustEmbedUnimplementedChainServer() {}
func (UnimplementedChainServer) testEmbeddedByValue()               {}

// UnsafeChainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainServer will
// result in compilation errors.
type UnsafeChainServer interface {
	mustEmbedUnimplementedChainServer()
}

func RegisterChainServer(s grpc.ServiceRegistrar, srv ChainServer) {
	// If the following call panics, it indicates UnimplementedChainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chain_ServiceDesc, srv)
}

func _Chain_GetChainBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChainBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServer).GetChainBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chain_GetChainBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServer).GetChainBlocks(ctx, req.(*GetChainBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chain_ServiceDesc is the grpc.ServiceDesc for Chain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainpulse.v1.Chain",
	HandlerType: (*ChainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChainBlocks",
			Handler:    _Chain_GetChainBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainpulse.proto",
}
